# This file contains information about GUI crates and projects in the Rust
# ecosystem.
#
# The allowed keys are as follows:
#
# # A crate on crates.io.
# [crate.my-crate]
# # The name of the crate. Defaults to the crate name, but may be capitalized
# # or named differently if desired.
# name = "MyCrate"
# # Any tags/categories that may be relevant about the crate.
# tags = ["tag1", "tag2"]
# # A description of the crate. Defaults to the description on crates.io.
# description = "A crate to do stuff"
# # Location of the crate's code repository.
# #
# # Defaults to what is specified on crates.io.
# repo = "https://mycrate.com/git"
# # Location of the crate's documentation.
# #
# # Defaults to what is specified on crates.io, or otherwise to docs.rs.
# docs = "https://docs.rs/mycrate"

[crate.gemgui]
name = "GemGui"
docs = "https://docs.rs/gemgui/latest/gemgui/"

[crate.gtk4]
name = "GTK 4"
tags = [
  "GTK",
  "Bindings",
]

[crate.rui]
docs = "https://docs.rs/rui/"
tags = [
  "winit",
  "iOS",
  "MacOS",
  "WebGPU",
]

[crate.dominator]
name = "Dominator"
docs = "https://docs.rs/dominator/latest/dominator/"

[crate.dioxus]
name = "Dioxus"
description = "Elegant React-like library for building user interfaces for desktop, web, mobile, SSR, liveview, and more."
docs = "https://docs.rs/dioxus/latest/dioxus/"

[crate.gladis]
docs = "https://docs.rs/gladis"
tags = [
  "GTK",
]

[crate.flutter_rust_bridge]
docs = "https://github.com/fzyzcjy/flutter_rust_bridge"
tags = [
  "Bindings",
]

[crate.relm4]
name = "Relm4"
tags = [
  "GTK",
  "Bindings",
  "MacOS",
  "CSS",
]

[crate.makepad]
name = "Makepad"
repo = "https://github.com/makepad/makepad"
description = "Makepad is a new VR, web and native-rendering UI framework."
tags = [
  "WebGPU",
]

[crate.winsafe]
name = "WinSafe"
description = "Win32 GUI and related APIs in safe, idiomatic Rust."
docs = "https://docs.rs/winsafe"
tags = [
  "Bindings",
  "WinApi",
]

[crate.fui_core]
name = "fui"
description = "MVVM-oriented (properties, observable collections, bindings), ui! macro, multiplatform, renderer-agnostic, with styles."
docs = "https://github.com/marek-g/rust-fui/blob/master/doc/SUMMARY.md"
tags = [
  "winit",
  "proc-macro",
]

[crate.slint]
skip-crates-io = true
name = "Slint"
repo = "https://github.com/slint-ui/slint"
description = "Slint is a toolkit to efficiently develop fluid graphical user interfaces for any display: embedded devices and desktop applications. It comes with a fast OpenGL renderer, a designer-friendly markup language and is written in Rust."
docs = "https://docs.rs/slint/"
tags = [
  "proc-macro",
  "winit",
  "Embedded",
  "MacOS",
]

[crate.native-windows-gui]
tags = [
  "Bindings",
  "proc-macro",
  "WinApi",
]

[crate.iui]
tags = [
  "Bindings",
]

[crate.lvgl]
docs = "https://github.com/rafaelcaricio/lvgl-rs"
tags = [
  "Bindings",
  "Embedded",
]

[crate.egui]
description = "Highly portable immediate mode GUI library in pure Rust"
docs = "https://docs.rs/egui"
tags = [
  "Immediate mode API",
]

[crate.imgui]
tags = [
  "Bindings",
  "Immediate mode API",
]

[crate.tauri]
skip-crates-io = true
repo = "https://github.com/tauri-apps/tauri"
description = "Tauri is a framework for building tiny, blazing fast binaries for all major desktop platforms."
docs = "https://tauri.studio/en/"
tags = [
  "HTML",
  "MacOS",
  "GTK",
]

[crate.vgtk]
tags = [
  "GTK",
]

[crate.conrod-core]
tags = [
  "Immediate mode API",
]

[crate.qt_widgets]
description = "Ritual Qt bindings"
docs = "https://rust-qt.github.io/qt/"
tags = [
  "Bindings",
  "Qt",
]

[crate.fltk]
description = "The FLTK crate is a crossplatform lightweight gui library which can be linked to statically to produce small, self-contained and fast binaries"
tags = [
  "Bindings",
  "FLTK",
]

[crate.kas]
name = "KAS"
description = "The toolKit Abstraction System leverages generics and macros to compose widgets with encapsulated user data, provides a powerful event-handling model and scales to at least 100'000 widgets per window."
docs = "https://docs.rs/kas"
tags = [
  "winit",
  "WebGPU",
  "proc-macro",
]

[crate.iced]
name = "Iced"
description = "A renderer-agnostic GUI library for Rust focused on simplicity and type-safety. Inspired by Elm."

[crate.core-foundation]
docs = "https://docs.rs/core-foundation/"
tags = [
  "Bindings",
  "MacOS",
]

[crate.cacao]
docs = "https://docs.rs/cacao/"
tags = [
  "MacOS",
  "iOS",
]

[crate.sciter-rs]
tags = [
  "HTML",
  "CSS",
]

[crate.azul]
name = "Azul"
tags = [
  "WebRender",
]

[crate.webrender]
name = "WebRender"
docs = "https://doc.servo.org/webrender/index.html"
tags = [
  "WebRender",
]

[crate.druid]
description = "Druid is an experimental Rust-native UI toolkit. Its main goal is to offer a polished user experience. There are many factors to this goal, including performance, a rich palette of interactions (hence a widget library to support them), and playing well with the native platform."
tags = [
  "piet",
]

[crate.orbtk]
name = "OrbTk"
description = "The Orbital Widget Toolkit is a multi platform (G)UI toolkit for building scalable user interfaces with the programming language Rust. It's based on the Entity Component System Pattern and provides a functional-reactive API."

[crate.rust-qt-binding-generator]
tags = [
  "Bindings",
  "Qt",
  "QML",
]

[crate.qmetaobject]
description = "A framework empowering everyone to create Qt/QML applications with Rust. It does so by building QMetaObjects at compile time, registering QML types (optionally via exposing QQmlExtensionPlugins) and providing idiomatic wrappers."
docs = "https://docs.rs/qmetaobject/"
tags = [
  "proc-macro",
  "Bindings",
  "Qt",
  "QML",
]

[crate.cxx-qt]
name = "CXX-Qt"
description = "CXX-Qt is a library that automatically generates code to transfer data between Rust and C++ through common interfaces such as QObjects that can be exposed directly into QML. It uses the cxx crate for safe interaction between Rust and C++."
docs = "https://kdab.github.io/cxx-qt/book/"
tags = [
  "Bindings",
  "Qt",
  "QML",
]

[crate.relm]
tags = [
  "Bindings",
  "GTK",
]

[crate.gtk]
name = "GTK"
description = "Rust bindings and wrappers for GLib, GDK 3, GTK+ 3 and Cairo."
docs = "https://gtk-rs.org/docs-src/"
tags = [
  "Bindings",
  "GTK",
]
