name: CLI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  lint-cli:
    name: Run cargo fmt and cargo clippy on the CLI script
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: cargo fmt
      run: cargo fmt --check

    - name: cargo clippy
      run: cargo clippy

  build:
    name: Builds project, fetching latest metadata and verifying configuration
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'

    steps:
    - uses: actions/checkout@v2

    - name: Build CLI
      run: cargo build --verbose

    - name: Update data
      run: |
        cargo run -- clean
        cargo run -- fetch

    - name: Build site
      uses: shalzz/zola-deploy-action@v0.17.2
      env:
        BUILD_ONLY: true
        BUILD_FLAGS: --drafts
        CHECK_LINKS: true

  deploy:
    name: Deploys to GH Pages
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
    - uses: actions/checkout@v2

    - name: Build CLI
      run: cargo build --verbose

    - name: Update data
      run: |
        cargo run -- clean
        cargo run -- fetch

    - name: Deploy site
      uses: shalzz/zola-deploy-action@v0.17.2
      env:
        PAGES_BRANCH: gh-pages
        CHECK_LINKS: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
